### ISSUE TITLE
Repository Is Missing IPBOFileEntry 

### ISSUE THREAD

**Issue by FlipperPlz** [jetelain/PboExplorer#1]
Was gonna make a fork and change the library for paramfiles to [DZConfigTools](https://github.com/FlipperPlz/DZConfigTools) to support the parsing of unbinarized config files, but when I opened the repository I happened to notice that BIS.PBO.IPBOFileEntry is not included in the repo. I would move that to the PboExplorer namespace if its not included by default in BisFileFormats.

**Comment by jetelain** [comment]
I'm using my own fork as Braini01 seems not active/not accepting pull requests. I have a pending PR for 9 months, so I've give up.
https://github.com/jetelain/bis-file-formats

**Comment by FlipperPlz** [comment]
Just saw this now, cheers!
